BlockvoteRegistrar.py dcpost@ucalgary.ca Blockvote2017 David dcpost@ucalgary.ca Blockvote2017 "Electrical/Software Engieering"
BlockvoteRegistrar.py dcpost@ucalgary.ca Blockvote2017 Michael mtheiber@ucalgary.ca Blockvote2017 "Mechanical Engineering"
BlockvoteRegistrar.py dcpost@ucalgary.ca Blockvote2017 Andrei abuiza@ucalgary.ca Blockvote2017 "Chemical Engineering"
BlockvoteRegistrar.py dcpost@ucalgary.ca Blockvote2017 Jose jmhm2012@gmail.com Blockvote2017 "Civil Engineering"
BlockvoteRegistrar.py dcpost@ucalgary.ca Blockvote2017 Connor czimmerm@ucalgary.ca Blockvote2017 "Geomatics Engieering"